export const regions = [
    // Seoul
    { label: '서울 강남구', value: '서울_강남구' },
    { label: '서울 강동구', value: '서울_강동구' },
    { label: '서울 강북구', value: '서울_강북구' },
    { label: '서울 강서구', value: '서울_강서구' },
    { label: '서울 관악구', value: '서울_관악구' },
    { label: '서울 광진구', value: '서울_광진구' },
    { label: '서울 구로구', value: '서울_구로구' },
    { label: '서울 금천구', value: '서울_금천구' },
    { label: '서울 노원구', value: '서울_노원구' },
    { label: '서울 도봉구', value: '서울_도봉구' },
    { label: '서울 동대문구', value: '서울_동대문구' },
    { label: '서울 동작구', value: '서울_동작구' },
    { label: '서울 마포구', value: '서울_마포구' },
    { label: '서울 서대문구', value: '서울_서대문구' },
    { label: '서울 서초구', value: '서울_서초구' },
    { label: '서울 성동구', value: '서울_성동구' },
    { label: '서울 성북구', value: '서울_성북구' },
    { label: '서울 송파구', value: '서울_송파구' },
    { label: '서울 양천구', value: '서울_양천구' },
    { label: '서울 영등포구', value: '서울_영등포구' },
    { label: '서울 용산구', value: '서울_용산구' },
    { label: '서울 은평구', value: '서울_은평구' },
    { label: '서울 종로구', value: '서울_종로구' },
    { label: '서울 중구', value: '서울_중구' },
    { label: '서울 중랑구', value: '서울_중랑구' },

    // Gyeonggi
    { label: '경기 고양시', value: '경기_고양시' },
    { label: '경기 과천시', value: '경기_과천시' },
    { label: '경기 광명시', value: '경기_광명시' },
    { label: '경기 구리시', value: '경기_구리시' },
    { label: '경기 군포시', value: '경기_군포시' },
    { label: '경기 김포시', value: '경기_김포시' },
    { label: '경기 남양주시', value: '경기_남양주시' },
    { label: '경기 부천시', value: '경기_부천시' },
    { label: '경기 성남시', value: '경기_성남시' },
    { label: '경기 수원시', value: '경기_수원시' },
    { label: '경기 시흥시', value: '경기_시흥시' },
    { label: '경기 안산시', value: '경기_안산시' },
    { label: '경기 안양시', value: '경기_안양시' },
    { label: '경기 용인시', value: '경기_용인시' },
    { label: '경기 의정부시', value: '경기_의정부시' },
    { label: '경기 파주시', value: '경기_파주시' },
    { label: '경기 평택시', value: '경기_평택시' },
    { label: '경기 하남시', value: '경기_하남시' },
    { label: '경기 화성시', value: '경기_화성시' },

    // Incheon
    { label: '인천 계양구', value: '인천_계양구' },
    { label: '인천 남동구', value: '인천_남동구' },
    { label: '인천 부평구', value: '인천_부평구' },
    { label: '인천 연수구', value: '인천_연수구' },
    { label: '인천 중구', value: '인천_중구' },
    { label: '인천 서구', value: '인천_서구' },

    // Others
    { label: '부산 해운대구', value: '부산_해운대구' },
    { label: '부산 수영구', value: '부산_수영구' },
    { label: '부산 부산진구', value: '부산진구' },
    { label: '대구 수성구', value: '대구_수성구' },
    { label: '대구 중구', value: '대구_중구' },
    { label: '광주 서구', value: '광주_서구' },
    { label: '광주 동구', value: '광주_동구' },
    { label: '대전 유성구', value: '대전_유성구' },
    { label: '대전 서구', value: '대전_서구' },
    { label: '울산 남구', value: '울산_남구' },
    { label: '울산 중구', value: '울산_중구' },
    { label: '세종특별자치시', value: '세종특별자치시' },
    { label: '강원 춘천시', value: '강원_춘천시' },
    { label: '강원 강릉시', value: '강원_강릉시' },
    { label: '강원 원주시', value: '강원_원주시' },
    { label: '제주 제주시', value: '제주_제주시' },
    { label: '제주 서귀포시', value: '제주_서귀포시' }
]
